name: Federation Specification Compatibility Test

on:
  pull_request:
    branches:
      - main
jobs:
  compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java (temurin@8)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt

      - name: Compatibility Test
        uses: apollographql/federation-subgraph-compatibility@v2
        with:
          # [Required] Docker Compose file to start up the subgraph
          compose: 'example/product/docker-compose.yaml'
          # [Required] Path to the GraphQL schema file
          schema: 'example/product/products.graphql'
          # GraphQL endpoint path, defaults to '' (empty)
          path: ''
          # GraphQL endpoint HTTP port, defaults to 4001
          port: 4001
          # Turn on debug mode with extra log info
          debug: false
          # Github Token / PAT for submitting PR comments
          token: ${{ secrets.GITHUB_TOKEN }}
          # Boolean flag to indicate whether any failing test should fail the script
          failOnWarning: false
          # Boolean flag to indicate whether any failing required functionality test should fail the script
          failOnRequired: false
          # Working directory to run the action from. Should be relative from the root of the project.
          workingDirectory: ''